version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/scraper"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    groups:
      maven-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/image-to-text"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/parser"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/image-rotator"
    schedule:
      interval: monthly
    groups:
      dart-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/minifier"
    schedule:
      interval: monthly
    groups:
      dart-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    groups:
      ci-dependencies:
        patterns:
          - "*"
