version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/sraper"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    groups:
       maven-dependencies:
          patterns:
            - "*"

  - package-ecosystem: npm
    directory: "/image-to-text"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    groups:
       npm-dependencies:
          patterns:
            - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    groups:
       ci-dependencies:
          patterns:
            - "*"
